- name: Install nftables .deb
  ansible.builtin.apt:
    name:
      - nftables

- name: Render template for config - /etc/nftables.conf
  ansible.builtin.template:
    src: default.nftables.conf.j2
    dest: /etc/nftables.conf